--SELECT FIRST_NAME, LAST_NAME 
--FROM CUSTOMER
--WHERE LAST_NAME LIKE 'S%'


select INVOICES.CUST_ID, INVOICE_LINE.INVOICE_NUM
from INVOICES, INVOICE_LINE
where INVOICES.INVOICE_NUM = INVOICE_LINE.INVOICE_NUM
-- Same as above
Select * FROM
INVOICES JOIN INVOICE_LINE
ON INVOICES.INVOICE_NUM = INVOICE_LINE.INVOICE_NUM


SELECT DESCRIPTION 
FROM ITEM 
WHERE ITEM_ID 
IN (SELECT ITEM_ID 
		FROM INVOICE_LINE WHERE INVOICE_NUM = '14233')


SELECT INVOICE_NUM, INVOICE_DATE FROM INVOICES
WHERE EXISTS (SELECT * FROM INVOICE_LINE WHERE INVOICES.INVOICE_NUM = INVOICE_LINE.INVOICE_NUM and ITEM_ID='KH81')

